nginx:
  image: nginx:latest
  ports:
    - "8080:80"
    - "443:443"
  container_name: ticademia_nginx
  volumes:
    - ./etc/nginx/ticademia.conf:/etc/nginx/conf.d/default.conf
    - ./code/:/var/www/html/ticademia
    - ./etc/certs:/etc/nginx/ssl
  links:
    - php

php:
  build: .
  dockerfile: /etc/docker/dockerfile_php_7
  container_name: ticademia_php
  volumes:
    - ./code/:/var/www/html/ticademia
  environment:
    - remote_host=10.254.254.254


